Normalization Problem

In [9]:
import numpy as np

X = np.random.random((5,5))
X_normalized = (X - X.mean())/ X.std()
X_normalized
np.save("X_normalized.npy",X_normalized)
print("Original Array:",X)
print()
print("Normalized Array:",X_normalized)

Original Array: [[0.54811531 0.49864612 0.30170036 0.02911267 0.43615176]
 [0.18607019 0.46144242 0.98337424 0.11631463 0.9117624 ]
 [0.17902519 0.02547449 0.9622018  0.52795015 0.70137408]
 [0.29466849 0.16640342 0.34258922 0.9546579  0.96230486]
 [0.92097881 0.2216785  0.04521045 0.80514064 0.92409809]]

Normalized Array: [[ 0.14213564 -0.00478679 -0.58971146 -1.39929103 -0.1903937 ]
 [-0.93313059 -0.11528098  1.43484527 -1.14030309  1.22215966]
 [-0.95405409 -1.41009635  1.37196359  0.08224555  0.59731088]
 [-0.61059596 -0.99154046 -0.46827244  1.34955837  1.37226969]
 [ 1.2495322  -0.82737466 -1.35148099  0.90549533  1.25879639]]


Divisible by 3 Problem

In [10]:
import numpy as np

num = list(range(1, 101))
A = np.array(num)
A = A ** 2
A.reshape(10,10)
div_by_3 = A[A % 3 == 0]
np.save("div_by_3.npy",div_by_3)
div_by_3

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])